#name: Main Branch Pipeline
#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - 'main'
#run-name: ${{ github.sha }} | ${{ github.event.head_commit.message }}
#jobs:
#  ci-step:
#    uses: raghudevopsb81/github-reusable-actions/.github/workflows/ci-main.yaml@main
#    with:
#      componentName: cart
#      SONAR_CLASS_PATH: " "
#    secrets:
#      NR_API_KEY: ${{ secrets.NR_API_KEY }}
#      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}


name: Cart CI Pipeline
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  tests:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  DEV:
    runs-on: self-hosted
    needs: tests
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  QA:
    runs-on: self-hosted
    needs: DEV
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo


  UAT:
    runs-on: self-hosted
    needs: QA
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo

  PROD:
    runs-on: self-hosted
    needs: UAT
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo      
      
      
